title: JASMIN Site
description: JASMIN web site implemented using Jekyll.
show_excerpts: true
google_tag_manager: true

plugins:
  - jekyll-feed

collections:
  staff_members:
    output: true
    permalink: /:collection/:name/
  about_items:
    output: true
    permalink: /:collection/:name/
  help_items:
    output: true
    permalink: /:collection/:name/
  users_items:
    output: true
    permalink: /:collection/:name/

collections_dir: collections

use_cacheBust: true

baseurl: "/"